services:
  db:
    image: postgres:15
    container_name: poke-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokehub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: poke-backend
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poke-frontend2
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

volumes:
  db_data:
